### PR TITLE
Add cloudfront full access to github-actions so it can invalidate the cache

### LINKED ISSUE #30: Need to grant github-actions access to list distributions and invalidate cache
We try to invalidate the cache, but unfortunately it [silently fails because of a permissions issue](https://github.com/marknooch/foodtrucks/runs/4917542016?check_suite_focus=true#step:11:11).   I manually provisioned the CloudFrontFullAccess policy on the github-actions IAM user as a workaround.

### PR DESCRIPTION
**Pull request by marknooch**
closes #30.

### CODE REVIEW

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

**Plan Failed**: This project is currently locked by an unapplied plan from pull #25. To continue, delete the lock from #25 or apply that plan and merge the pull request.

Once the lock is released, comment `atlantis plan` here to re-plan.

**Comment by marknooch** [comment]
atlantis plan

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -out \"/home/atlantis/.atlantis/repos/marknooch/foodtrucks/31/default/terraform/default.tfplan\"" in "/home/atlantis/.atlantis/repos/marknooch/foodtrucks/31/default/terraform": exit status 1
╷
│ Error: Provider configuration not present
│ 
│ To work with aws_acm_certificate_validation.cert-validation (orphan) its
│ original provider configuration at
│ provider["registry.terraform.io/hashicorp/aws"].acm_provider is required,
│ but it has been removed. This occurs when a provider configuration is
│ removed while objects created by that provider still exist in the state.
│ Re-add the provider configuration to destroy
│ aws_acm_certificate_validation.cert-validation (orphan), after which you
│ can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with aws_acm_certificate.ssl-certificate (orphan) its original
│ provider configuration at
│ provider["registry.terraform.io/hashicorp/aws"].acm_provider is required,
│ but it has been removed. This occurs when a provider configuration is
│ removed while objects created by that provider still exist in the state.
│ Re-add the provider configuration to destroy
│ aws_acm_certificate.ssl-certificate (orphan), after which you can remove
│ the provider configuration again.
╵

```
</details>

**Comment by marknooch** [comment]
atlantis plan

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -out \"/home/atlantis/.atlantis/repos/marknooch/foodtrucks/31/default/terraform/default.tfplan\"" in "/home/atlantis/.atlantis/repos/marknooch/foodtrucks/31/default/terraform": exit status 1
╷
│ Error: Provider configuration not present
│ 
│ To work with aws_acm_certificate_validation.cert-validation (orphan) its
│ original provider configuration at
│ provider["registry.terraform.io/hashicorp/aws"].acm_provider is required,
│ but it has been removed. This occurs when a provider configuration is
│ removed while objects created by that provider still exist in the state.
│ Re-add the provider configuration to destroy
│ aws_acm_certificate_validation.cert-validation (orphan), after which you
│ can remove the provider configuration again.
╵
╷
│ Error: Provider configuration not present
│ 
│ To work with aws_acm_certificate.ssl-certificate (orphan) its original
│ provider configuration at
│ provider["registry.terraform.io/hashicorp/aws"].acm_provider is required,
│ but it has been removed. This occurs when a provider configuration is
│ removed while objects created by that provider still exist in the state.
│ Re-add the provider configuration to destroy
│ aws_acm_certificate.ssl-certificate (orphan), after which you can remove
│ the provider configuration again.
╵

```
</details>

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_iam_user_policy_attachment.github-actions will be created
+ resource "aws_iam_user_policy_attachment" "github-actions" {
      + id         = (known after apply)
      + policy_arn = "arn:aws:iam::aws:policy/CloudFrontFullAccess"
      + user       = "github-actions"
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by marknooch** [comment]
atlantis apply

**Comment by atlantis-green** [comment]
Ran Apply for dir: `terraform` workspace: `default`

```diff
aws_iam_user_policy_attachment.github-actions: Creating...
aws_iam_user_policy_attachment.github-actions: Creation complete after 0s [id=github-actions-20220124065024773400000001]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```

**Comment by atlantis-green** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform` workspace: `default`

**Pull request merged**
