### PR TITLE
Git the data

### LINKED ISSUE #4: Obtain and process the food truck data
Create a github action which does the following:

- [x] Identifies the open food trucks using [the list of permits](https://data.sfgov.org/Economy-and-Community/Mobile-Food-Facility-Permit/rqzj-sfat) to filter the ones that have an approved status and [the schedule data](https://data.sfgov.org/Economy-and-Community/Mobile-Food-Schedule/jjew-r69b) to filter the ones that are currently open and produce a GeoJSON file.
- [x] commit that file to the data branch
- [x] #12

Steps where we want to test
- [x] After we get the two files, make sure that the columns we care about are there.  This protects us from our upstream data provider.  If they aren't commit the files we received to the error folder in the data branch and error the github action.
- [x] #11

### LINKED ISSUE #12: deploy the file to our home on the internet if the two tests below don't fail
- [x] #13
- [ ] Update the github actions file so it uses the secrets to update the files in s3

### PR DESCRIPTION
**Pull request by marknooch**
closes #12 , closes #4

### CODE REVIEW

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_s3_bucket_policy.github-actions will be updated in-place
~ resource "aws_s3_bucket_policy" "github-actions" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Resource  = "arn:aws:s3:::terraform-20220121192859548500000001" -> "arn:aws:s3:::terraform-20220121192859548500000001/*"
                        # (4 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by marknooch** [comment]
atlantis apply

**Comment by atlantis-green** [comment]
Ran Apply for dir: `terraform` workspace: `default`

```diff
aws_s3_bucket_policy.github-actions: Modifying... [id=terraform-20220121192859548500000001]
aws_s3_bucket_policy.github-actions: Modifications complete after 0s [id=terraform-20220121192859548500000001]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.


```

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_s3_bucket_policy.github-actions has changed
~ resource "aws_s3_bucket_policy" "github-actions" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode( # whitespace changes
            {
                Statement = [
                    {
                        Action    = "s3:*"
                        Effect    = "Allow"
                        Principal = {
                            AWS = "arn:aws:iam::246850902828:user/github-actions"
                        }
                        Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                        Sid       = ""
                    },
                ]
                Version   = "2012-10-17"
            }
        )
        # (1 unchanged attribute hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # github_actions_secret.S3_BUCKET will be created
+ resource "github_actions_secret" "S3_BUCKET" {
      + created_at      = (known after apply)
      + id              = (known after apply)
      + plaintext_value = (sensitive value)
      + repository      = "foodtrucks"
      + secret_name     = "S3_BUCKET"
      + updated_at      = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by marknooch** [comment]
atlantis apply

**Comment by atlantis-green** [comment]
Ran Apply for dir: `terraform` workspace: `default`

```diff
github_actions_secret.S3_BUCKET: Creating...
github_actions_secret.S3_BUCKET: Creation complete after 2s [id=foodtrucks:S3_BUCKET]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```

**Comment by atlantis-green** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform` workspace: `default`

**Pull request merged**
