### PR TITLE
bootstrap the s3 backend

### PR DESCRIPTION
**Pull request by marknooch**

### CODE REVIEW

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform-bootstrap` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
 <= read (data resources)

Terraform will perform the following actions:

  # data.aws_iam_policy_document.atlantis will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "atlantis"  {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "s3:*",
            ]
          + resources = [
              + (known after apply),
            ]

          + principals {
              + identifiers = [
                  + "AIDATS6LV3MWIUVU5CTHE",
                ]
              + type        = "AWS"
            }
        }
    }

  # aws_s3_bucket.faf-tfstate will be created
+ resource "aws_s3_bucket" "faf-tfstate" {
      + acceleration_status         = (known after apply)
      + acl                         = "private"
      + arn                         = (known after apply)
      + bucket                      = "faf-tfstate"
      + bucket_domain_name          = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags_all                    = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)

      + grant {
          + id          = "864bf9eefaf9c733be7b31d2e9ea713d92516fe1418ce64ff72c9054d62c9021"
          + permissions = [
              + "FULL_CONTROL",
            ]
          + type        = "CanonicalUser"
        }

      + versioning {
          + enabled    = true
          + mfa_delete = false
        }
    }

  # aws_s3_bucket_policy.atlantis will be created
+ resource "aws_s3_bucket_policy" "atlantis" {
      + bucket = (known after apply)
      + id     = (known after apply)
      + policy = (known after apply)
    }

Plan: 2 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform-bootstrap`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform-bootstrap%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform-bootstrap`
</details>
Plan: 2 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by marknooch** [comment]
atlantis apply

**Comment by atlantis-green** [comment]
Ran Apply for dir: `terraform-bootstrap` workspace: `default`

**Apply Error**
```
running "/usr/local/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/marknooch/foodtrucks/9/default/terraform-bootstrap/default.tfplan\"" in "/home/atlantis/.atlantis/repos/marknooch/foodtrucks/9/default/terraform-bootstrap": exit status 1
aws_s3_bucket.faf-tfstate: Creating...
╷
│ Error: Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
│ 	status code: 409, request id: KWPYX34FW3G8AX3H, host id: NdGkKc0UsjjlWTqtkTZUg3QcY7vM1oK5UJQjAJK/EoVHYrU1ezHAYbr+zV6BA4a+8chJJbn1kD8=
│ 
│   with aws_s3_bucket.faf-tfstate,
│   on main.tf line 16, in resource "aws_s3_bucket" "faf-tfstate":
│   16: resource "aws_s3_bucket" "faf-tfstate" {
│ 
╵

```

**Comment by marknooch** [comment]
Merging.  I was curious how atlantis would handle this.  It is having problems because I created the bucket with my account and shared access with it with atlantis.

**Comment by atlantis-green** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform-bootstrap` workspace: `default`

**Pull request merged**
