### PR TITLE
Add index.html and adjust settings so it is accessible

### LINKED ISSUE #5: Create a webpage which renders the GeoJSON data
[Leaflet has an example](https://github.com/Leaflet/Leaflet/tree/main/docs/examples/geojson) to use as a starting place.

### LINKED ISSUE #18: Switch to Mapbox GL SDK
Switch to Mapbox GL SDK to take advantage of their features.  Use [this example](https://docs.mapbox.com/mapbox-gl-js/example/external-geojson/)

### PR DESCRIPTION
**Pull request by marknooch**
closes #5 , closes #18

### CODE REVIEW

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -out \"/home/atlantis/.atlantis/repos/marknooch/foodtrucks/17/default/terraform/default.tfplan\"" in "/home/atlantis/.atlantis/repos/marknooch/foodtrucks/17/default/terraform": exit status 1
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 41, in data "aws_iam_policy_document" "public-read":
│   41:   actions = [ "s3:GetObject", "s3:GetObjectVersion", "s3:ListBucket"]
│ 
│ An argument named "actions" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 42, in data "aws_iam_policy_document" "public-read":
│   42:   resources = ["${aws_s3_bucket.s3_home.arn}/*"]
│ 
│ An argument named "resources" is not expected here.
╵

```
</details>

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket_policy.public-read will be created
+ resource "aws_s3_bucket_policy" "public-read" {
      + bucket = "terraform-20220121192859548500000001"
      + id     = (known after apply)
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = [
                          + "s3:ListBucket",
                          + "s3:GetObjectVersion",
                          + "s3:GetObject",
                        ]
                      + Effect    = "Allow"
                      + Principal = {
                          + Group = "http://acs.amazonaws.com/groups/global/AllUsers"
                        }
                      + Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by marknooch** [comment]
atlantis apply

**Comment by atlantis-green** [comment]
Ran Apply for dir: `terraform` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/marknooch/foodtrucks/17/default/terraform/default.tfplan\"" in "/home/atlantis/.atlantis/repos/marknooch/foodtrucks/17/default/terraform": exit status 1
aws_s3_bucket_policy.public-read: Creating...
aws_s3_bucket_policy.public-read: Still creating... [10s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [20s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [30s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [40s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [50s elapsed]
╷
│ Error: Error putting S3 policy: MalformedPolicy: Invalid policy syntax.
│ 	status code: 400, request id: Z9QP6GSG81WXSE4E, host id: j3sI9J0W1pwni0d9PN3WEGG5+GJcM0Yzq7Z4q5ALrZ2xrUUnSxf0QGnDaUdARWSXOISQJok0XYE=
│ 
│   with aws_s3_bucket_policy.public-read,
│   on main.tf line 46, in resource "aws_s3_bucket_policy" "public-read":
│   46: resource "aws_s3_bucket_policy" "public-read" {
│ 
╵

```
</details>

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket_policy.public-read will be created
+ resource "aws_s3_bucket_policy" "public-read" {
      + bucket = "terraform-20220121192859548500000001"
      + id     = (known after apply)
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = [
                          + "s3:ListBucket",
                          + "s3:GetObjectVersion",
                          + "s3:GetObject",
                        ]
                      + Effect    = "Allow"
                      + Principal = {
                          + Group = "http://acs.amazonaws.com/groups/global/AllUsers"
                        }
                      + Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket_policy.public-read will be created
+ resource "aws_s3_bucket_policy" "public-read" {
      + bucket = "terraform-20220121192859548500000001"
      + id     = (known after apply)
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = [
                          + "s3:ListBucket",
                          + "s3:GetObjectVersion",
                          + "s3:GetObject",
                        ]
                      + Effect    = "Allow"
                      + Principal = {
                          + Group = "http://acs.amazonaws.com/groups/global/AllUsers"
                        }
                      + Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket_policy.public-read will be created
+ resource "aws_s3_bucket_policy" "public-read" {
      + bucket = "terraform-20220121192859548500000001"
      + id     = (known after apply)
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = [
                          + "s3:ListBucket",
                          + "s3:GetObjectVersion",
                          + "s3:GetObject",
                        ]
                      + Effect    = "Allow"
                      + Principal = {
                          + Group = "http://acs.amazonaws.com/groups/global/AllUsers"
                        }
                      + Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket_policy.public-read will be created
+ resource "aws_s3_bucket_policy" "public-read" {
      + bucket = "terraform-20220121192859548500000001"
      + id     = (known after apply)
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = [
                          + "s3:ListBucket",
                          + "s3:GetObjectVersion",
                          + "s3:GetObject",
                        ]
                      + Effect    = "Allow"
                      + Principal = {
                          + Group = "http://acs.amazonaws.com/groups/global/AllUsers"
                        }
                      + Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket_policy.public-read will be created
+ resource "aws_s3_bucket_policy" "public-read" {
      + bucket = "terraform-20220121192859548500000001"
      + id     = (known after apply)
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = [
                          + "s3:ListBucket",
                          + "s3:GetObjectVersion",
                          + "s3:GetObject",
                        ]
                      + Effect    = "Allow"
                      + Principal = "*"
                      + Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by marknooch** [comment]
atlantis apply

**Comment by atlantis-green** [comment]
Ran Apply for dir: `terraform` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/marknooch/foodtrucks/17/default/terraform/default.tfplan\"" in "/home/atlantis/.atlantis/repos/marknooch/foodtrucks/17/default/terraform": exit status 1
aws_s3_bucket_policy.public-read: Creating...
aws_s3_bucket_policy.public-read: Still creating... [10s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [20s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [30s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [40s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [50s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [1m0s elapsed]
╷
│ Error: Error putting S3 policy: MalformedPolicy: Action does not apply to any resource(s) in statement
│ 	status code: 400, request id: WWD3SGMY8EZZ1109, host id: rky358L249FWZbH4Fj062pm2NaLoWEoj/2yA/R/XN1ykuBDxh3O9PDwxY+jvRF9xVjWD1Afg8jc=
│ 
│   with aws_s3_bucket_policy.public-read,
│   on main.tf line 46, in resource "aws_s3_bucket_policy" "public-read":
│   46: resource "aws_s3_bucket_policy" "public-read" {
│ 
╵

```
</details>

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket_policy.public-read will be created
+ resource "aws_s3_bucket_policy" "public-read" {
      + bucket = "terraform-20220121192859548500000001"
      + id     = (known after apply)
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = [
                          + "s3:ListBucket",
                          + "s3:GetObjectVersion",
                          + "s3:GetObject",
                        ]
                      + Effect    = "Allow"
                      + Principal = "*"
                      + Resource  = "arn:aws:s3:::terraform-20220121192859548500000001"
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by marknooch** [comment]
atlantis apply

**Comment by atlantis-green** [comment]
Ran Apply for dir: `terraform` workspace: `default`

**Apply Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform apply -input=false \"/home/atlantis/.atlantis/repos/marknooch/foodtrucks/17/default/terraform/default.tfplan\"" in "/home/atlantis/.atlantis/repos/marknooch/foodtrucks/17/default/terraform": exit status 1
aws_s3_bucket_policy.public-read: Creating...
aws_s3_bucket_policy.public-read: Still creating... [10s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [20s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [30s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [40s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [50s elapsed]
aws_s3_bucket_policy.public-read: Still creating... [1m0s elapsed]
╷
│ Error: Error putting S3 policy: MalformedPolicy: Action does not apply to any resource(s) in statement
│ 	status code: 400, request id: GM3TQY9D9VZX043P, host id: nqF35sb/OKLN7hmE1qqeU92+l11Yd3RBAL8u5Nuu31dpiDOJBlTSGhz1St0pLoQVDWrOwrSot8o=
│ 
│   with aws_s3_bucket_policy.public-read,
│   on main.tf line 46, in resource "aws_s3_bucket_policy" "public-read":
│   46: resource "aws_s3_bucket_policy" "public-read" {
│ 
╵

```
</details>

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_s3_bucket_policy.public-read will be created
+ resource "aws_s3_bucket_policy" "public-read" {
      + bucket = "terraform-20220121192859548500000001"
      + id     = (known after apply)
      + policy = jsonencode(
            {
              + Statement = [
                  + {
                      + Action    = [
                          + "s3:GetObjectVersion",
                          + "s3:GetObject",
                        ]
                      + Effect    = "Allow"
                      + Principal = "*"
                      + Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                      + Sid       = ""
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
    }

Plan: 1 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by marknooch** [comment]
atlantis apply

**Comment by atlantis-green** [comment]
Ran Apply for dir: `terraform` workspace: `default`

```diff
aws_s3_bucket_policy.public-read: Creating...
aws_s3_bucket_policy.public-read: Creation complete after 0s [id=terraform-20220121192859548500000001]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_s3_bucket_policy.github-actions has changed
~ resource "aws_s3_bucket_policy" "github-actions" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Action    = "s3:*" -> [
                          + "s3:GetObjectVersion",
                          + "s3:GetObject",
                        ]
                      ~ Principal = {
                          - AWS = "arn:aws:iam::246850902828:user/github-actions"
                        } -> "*"
                        # (3 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }

  # aws_s3_bucket_policy.public-read has changed
~ resource "aws_s3_bucket_policy" "public-read" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode( # whitespace changes
            {
                Statement = [
                    {
                        Action    = [
                            "s3:GetObjectVersion",
                            "s3:GetObject",
                        ]
                        Effect    = "Allow"
                        Principal = "*"
                        Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                        Sid       = ""
                    },
                ]
                Version   = "2012-10-17"
            }
        )
        # (1 unchanged attribute hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_s3_bucket_policy.github-actions will be updated in-place
~ resource "aws_s3_bucket_policy" "github-actions" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Action    = [
                          - "s3:GetObjectVersion",
                          - "s3:GetObject",
                        ] -> "s3:*"
                      ~ Principal = "*" -> {
                          + AWS = "arn:aws:iam::246850902828:user/github-actions"
                        }
                        # (3 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_s3_bucket_policy.github-actions has changed
~ resource "aws_s3_bucket_policy" "github-actions" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Action    = "s3:*" -> [
                          + "s3:GetObjectVersion",
                          + "s3:GetObject",
                        ]
                      ~ Principal = {
                          - AWS = "arn:aws:iam::246850902828:user/github-actions"
                        } -> "*"
                        # (3 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }

  # aws_s3_bucket_policy.public-read has changed
~ resource "aws_s3_bucket_policy" "public-read" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode( # whitespace changes
            {
                Statement = [
                    {
                        Action    = [
                            "s3:GetObjectVersion",
                            "s3:GetObject",
                        ]
                        Effect    = "Allow"
                        Principal = "*"
                        Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                        Sid       = ""
                    },
                ]
                Version   = "2012-10-17"
            }
        )
        # (1 unchanged attribute hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_s3_bucket_policy.github-actions will be updated in-place
~ resource "aws_s3_bucket_policy" "github-actions" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Action    = [
                          - "s3:GetObjectVersion",
                          - "s3:GetObject",
                        ] -> "s3:*"
                      ~ Principal = "*" -> {
                          + AWS = "arn:aws:iam::246850902828:user/github-actions"
                        }
                        # (3 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/local/bin/terraform plan -input=false -refresh -out \"/home/atlantis/.atlantis/repos/marknooch/foodtrucks/17/default/terraform/default.tfplan\"" in "/home/atlantis/.atlantis/repos/marknooch/foodtrucks/17/default/terraform": exit status 1
╷
│ Error: Reference to undeclared resource
│ 
│   on main.tf line 80, in resource "github_actions_secret" "AWS_ACCESS_KEY_ID":
│   80:   plaintext_value         = aws_iam_access_key.github-actions.id
│ 
│ A managed resource "aws_iam_access_key" "github-actions" has not been
│ declared in the root module.
╵
╷
│ Error: Reference to undeclared resource
│ 
│   on main.tf line 86, in resource "github_actions_secret" "AWS_SECRET_ACCESS_KEY":
│   86:   plaintext_value         = aws_iam_access_key.github-actions.secret
│ 
│ A managed resource "aws_iam_access_key" "github-actions" has not been
│ declared in the root module.
╵

```
</details>

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_s3_bucket_policy.github-actions has changed
~ resource "aws_s3_bucket_policy" "github-actions" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Action    = "s3:*" -> [
                          + "s3:GetObjectVersion",
                          + "s3:GetObject",
                        ]
                      ~ Principal = {
                          - AWS = "arn:aws:iam::246850902828:user/github-actions"
                        } -> "*"
                        # (3 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }

  # aws_s3_bucket_policy.public-read has changed
~ resource "aws_s3_bucket_policy" "public-read" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode( # whitespace changes
            {
                Statement = [
                    {
                        Action    = [
                            "s3:GetObjectVersion",
                            "s3:GetObject",
                        ]
                        Effect    = "Allow"
                        Principal = "*"
                        Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                        Sid       = ""
                    },
                ]
                Version   = "2012-10-17"
            }
        )
        # (1 unchanged attribute hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place
- destroy

Terraform will perform the following actions:

  # aws_s3_bucket_policy.github-actions will be destroyed
  # (because aws_s3_bucket_policy.github-actions is not in configuration)
- resource "aws_s3_bucket_policy" "github-actions" {
      - bucket = "terraform-20220121192859548500000001" -> null
      - id     = "terraform-20220121192859548500000001" -> null
      - policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = [
                          - "s3:GetObjectVersion",
                          - "s3:GetObject",
                        ]
                      - Effect    = "Allow"
                      - Principal = "*"
                      - Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
    }

  # aws_s3_bucket_policy.public-read will be updated in-place
~ resource "aws_s3_bucket_policy" "public-read" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode(
          ~ {
              ~ Statement = [
                    {
                        Action    = [
                            "s3:GetObjectVersion",
                            "s3:GetObject",
                        ]
                        Effect    = "Allow"
                        Principal = "*"
                        Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                        Sid       = ""
                    },
                  + {
                      + Action    = "s3:*"
                      + Effect    = "Allow"
                      + Principal = {
                          + AWS = "arn:aws:iam::246850902828:user/github-actions"
                        }
                      + Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                      + Sid       = ""
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 1 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 0 to add, 1 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by marknooch** [comment]
atlantis apply

**Comment by atlantis-green** [comment]
Ran Apply for dir: `terraform` workspace: `default`

```diff
aws_s3_bucket_policy.github-actions: Destroying... [id=terraform-20220121192859548500000001]
aws_s3_bucket_policy.public-read: Modifying... [id=terraform-20220121192859548500000001]
aws_s3_bucket_policy.github-actions: Destruction complete after 0s
aws_s3_bucket_policy.public-read: Modifications complete after 0s [id=terraform-20220121192859548500000001]

Apply complete! Resources: 0 added, 1 changed, 1 destroyed.


```

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_s3_bucket_policy.public-read has changed
~ resource "aws_s3_bucket_policy" "public-read" {
        id     = "terraform-20220121192859548500000001"
      ~ policy = jsonencode( # whitespace changes
            {
                Statement = [
                    {
                        Action    = [
                            "s3:GetObjectVersion",
                            "s3:GetObject",
                        ]
                        Effect    = "Allow"
                        Principal = "*"
                        Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                        Sid       = ""
                    },
                    {
                        Action    = "s3:*"
                        Effect    = "Allow"
                        Principal = {
                            AWS = "arn:aws:iam::246850902828:user/github-actions"
                        }
                        Resource  = "arn:aws:s3:::terraform-20220121192859548500000001/*"
                        Sid       = ""
                    },
                ]
                Version   = "2012-10-17"
            }
        )
        # (1 unchanged attribute hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like
to update the Terraform state to match, create and apply a refresh-only plan.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>

**Note: Objects have changed outside of Terraform**
No changes. Your infrastructure matches the configuration.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by marknooch** [comment]
atlantis apply

**Comment by atlantis-green** [comment]
Ran Apply for dir: `terraform` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.


```

**Comment by atlantis-green** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform` workspace: `default`

**Pull request merged**
