### PR TITLE
Terraform secrets redeux

### PR DESCRIPTION
**Pull request by marknooch**
#13

### CODE REVIEW

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

**Plan Failed**: This project is currently locked by an unapplied plan from pull #14. To continue, delete the lock from #14 or apply that plan and merge the pull request.

Once the lock is released, comment `atlantis plan` here to re-plan.

**Comment by marknooch** [comment]
atlantis plan

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

```diff

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by atlantis-green** [comment]
Ran Plan for dir: `terraform` workspace: `default`

```diff

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.greenatlantis.ga/lock?id=marknooch%252Ffoodtrucks%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by atlantis-green** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform` workspace: `default`

**Pull request merged**
